### PR TITLE
Update to play 2.8

### PR DESCRIPTION
**Pull request by tanacasino**
- Update to 2.8.0
- Drop Scala 2.11 support

### CODE REVIEW

**Review by gmethvin — CHANGES_REQUESTED** [review]
Thanks for the pull request. I think it's ok to remove scala 2.11, but the build is failing because you need to also remove it from `.travis.yml`.

**Comment by tanacasino** [comment]
Thanks. I fixed it.

**Comment by tanacasino** [comment]
@gmethvin Do you have any plan to release 2.8.x support version?

**Comment by gmethvin** [comment]
@tanacasino Does the currently released version not work for 2.8.x? I don't think there were any ConfigLoader API changes in 2.8.x.

**Comment by tanacasino** [comment]
Thanks for reply. I'll check it.

**Pull request merged**
